version: '3.1'

services: 

  spark-pg:
    image: "postgres:latest"
    environment: 
      POSTGRES_PASSWORD: spark
      POSTGRES_USER: spark
      POSTGRES_DB: spark
    volumes:
      - /var/lib/postgresql/data
    ports: 
      - "15432:5432"
    restart: always

